### ISSUE TITLE
Simon Won't run the models

### ISSUE THREAD

**Issue by dr-abhi86** [genular/simon-frontend#119] opened 2022-06-27 14:56 UTC
Dear Simon team,

I just started on SIMON and used the SISA dataset to run 6 models as suggested in the manuscript. My data is uploaded and I have selected a few models and hit process .

Since yesterday I see no changes in my dashboard.
<img width="1027" alt="Screen Shot 2022-06-27 at 9 53 00 AM" src="https://user-images.githubusercontent.com/107630328/175970276-d3187d03-b88c-41c2-b22d-505b8d6234a6.png">

Can you help me get started with the analysis here.

Can you make and post a video right from the beginning as how to import the data. 
Select various model and options 
how to request for processing.

The paper has the video of steps after your models has been processed by SIMON.

Can you do it for a demo dataset such as SISA so the users can follow step by step and recreate the exact analysis.

This would be really helpful to me and a lot of users who are getting started.

Thank you for this great tool, please help me progress with it.

Best,
Abhi

**Comment by LogIN-** [comment] 2022-06-30 08:23
Hi @dr-abhi86,

Please reinstall SIMON and try again in some cases cron pid file is not deleted and new queue is not started. I just made a fix for this error and it will be available in next SIMON version.

To reinstall please delete any existing SIMON instances:

```
docker stop genular
docker system prune -a --volumes
```

And install it as usuall:

```
docker run --rm --detach --name genular --tty --interactive --env IS_DOCKER='true' --env TZ=Europe/London --oom-kill-disable --volume genular_data_latest:/mnt/usrdata --publish 3010:3010 --publish 3011:3011 --publish 3012:3012 --publish 3013:3013 genular/simon:latest
```

Thanks for reporting the issue.

**Closed by LogIN-** 2022-06-30 08:23 UTC

**Comment by leeanapeters** [comment] 2022-08-15 16:25
Hi, was this fixed?

I have pulled the latest version of simon I believe, but I am also encountering this issue.

Any help would be much appreciated 

Leeana

**Comment by LogIN-** [comment] 2022-08-23 09:41
Hi @leeanapeters,

Please upload your SIMON Log files. This issue if user system specific and it is impossible to tell without looking at log files where is a problem.

It could be for example: 
 - bad docker configuration (not enough CPUs / RAM allocated) , bad CSV file format or something else.

Since this issue is not reproducible this ticket is closed.
