### ISSUE TITLE
Pause/stop queue when it is running

### ISSUE THREAD

**Issue by krassowski** [genular/simon-frontend#122] opened 2022-06-28 11:19 UTC
**Is your feature request related to a problem? Please describe.**

I cannot stop a queue that I scheduled to run.

**Describe the solution you'd like**

I would like to be able to stop a running queue. There is a button to stop queue but it is disabled.

![Screenshot from 2022-06-28 12-18-34](https://user-images.githubusercontent.com/5832902/176166420-3f166cc4-3956-4a37-a34f-64cfbf5f8006.png)

![Screenshot from 2022-06-28 12-18-57](https://user-images.githubusercontent.com/5832902/176166382-c77dc332-14af-4a81-bc97-0c907e8eb52d.png)

I would like it to work.

Edit: duplicate of #47

**Comment by krassowski** [comment] 2022-06-28 11:20
When I press the delete icon it says "Cannot select queue task. It is still not finished or no any Completed Models found."

**Comment by krassowski** [comment] 2022-06-28 11:22
But there is a workaround: If I select the queue using a checkbox and then press on another delete (bin) icon, but not the one in the "Operations" section, but the one above the table (next to "export table") it seems to work:

![Screenshot from 2022-06-28 12-21-55](https://user-images.githubusercontent.com/5832902/176166836-82fa252b-7dac-4f5c-a196-48bd0ccf98b4.png)

**Comment by LogIN-** [comment] 2022-06-28 12:00
Duplicate of #47

**Closed by LogIN-** 2022-06-28 12:00 UTC
